#pragma once
#include "resources.h"
#include <algorithm>
// Bounds-checked reader for the imported MiiBody.szs, NW4R MDL0 v11 and its stand pose.
// Format reference: https://github.com/magcius/noclip.website/blob/master/src/rres/brres.ts
namespace kartpad::mii {
struct BodyPart { Mesh mesh; Image texture, lightMap, highlightMap; bool favoriteColor=false; };
struct BodyModel { std::vector<BodyPart> parts; float neckY=0, neckZ=0; std::array<float,3> headAttachment{1,0,0}; };
class BodyResources {
    struct Entry { std::string name;size_t offset; };
    struct Matrix {
        std::array<float,12> v{1,0,0,0,0,1,0,0,0,0,1,0};
        Matrix operator*(const Matrix &b)const {Matrix c;for(int i=0;i<3;i++)for(int j=0;j<4;j++){c.v[i*4+j]=j==3?v[i*4+3]:0;for(int k=0;k<3;k++)c.v[i*4+j]+=v[i*4+k]*b.v[k*4+j];}return c;}
        std::array<float,3> Apply(std::array<float,3>a,bool normal=false)const{std::array<float,3>b{};for(int i=0;i<3;i++){b[i]=normal?0:v[i*4+3];for(int j=0;j<3;j++)b[i]+=v[i*4+j]*a[j];}return b;}
    };
    std::array<BodyModel,2> models;
    static float F(ResourceReader r,size_t p){float f=std::bit_cast<float>(r.U32(p));if(!std::isfinite(f))throw std::invalid_argument("Invalid Mii body coordinate.");return f;}
    static std::string Name(ResourceReader r,size_t p){std::string s;for(unsigned i=0;i<256;i++){auto c=r.U8(p+i);if(!c)return s;s+=char(c);}throw std::invalid_argument("Invalid Mii body name.");}
    static std::vector<Entry> Dictionary(ResourceReader r,size_t p){std::vector<Entry>d;if(!p)return d;auto n=r.U32(p+4);if(n>1024)throw std::invalid_argument("Invalid body resource dictionary.");for(unsigned i=0;i<n;i++){size_t e=p+24+i*16;d.push_back({Name(r,p+r.U32(e+8)),p+r.U32(e+12)});}return d;}
    static size_t Find(const std::vector<Entry>&d,const std::string&name){for(auto&e:d)if(e.name==name)return e.offset;throw std::invalid_argument("Missing Mii body resource: "+name);}
    static Matrix SRT(const std::array<float,9>&a){Matrix scale;scale.v={a[0],0,0,0,0,a[1],0,0,0,0,a[2],0};Matrix rx,ry,rz;float x=a[3]*.01745329252f,y=a[4]*.01745329252f,z=a[5]*.01745329252f;rx.v={1,0,0,0,0,cosf(x),-sinf(x),0,0,sinf(x),cosf(x),0};ry.v={cosf(y),0,sinf(y),0,0,1,0,0,-sinf(y),0,cosf(y),0};rz.v={cosf(z),-sinf(z),0,0,sinf(z),cosf(z),0,0,0,0,1,0};auto m=rz*ry*rx*scale;m.v[3]=a[6];m.v[7]=a[7];m.v[11]=a[8];return m;}
    static Image Texture(ResourceReader r,size_t t){unsigned w=r.U16(t+28),h=r.U16(t+30);if(!w||!h||w>1024||h>1024||r.U32(t+32)!=14)throw std::invalid_argument("Unsupported Mii body texture.");Image out{w,h,std::vector<uint8_t>(w*h*4)};size_t p=t+r.U32(t+16);
        // GX CMPR: four 4x4 DXT1 blocks per 8x8 tile, big-endian endpoints/selectors.
        for(unsigned y=0;y<h;y+=8)for(unsigned x=0;x<w;x+=8)for(unsigned b=0;b<4;b++,p+=8){auto c0=r.U16(p),c1=r.U16(p+2);std::array<std::array<unsigned,4>,4> colors{};auto rgb=[](unsigned v){return std::array<unsigned,4>{((v>>11)&31)*255/31,((v>>5)&63)*255/63,(v&31)*255/31,255};};colors[0]=rgb(c0);colors[1]=rgb(c1);for(int c=0;c<3;c++){colors[2][c]=c0>c1?(2*colors[0][c]+colors[1][c])/3:(colors[0][c]+colors[1][c])/2;colors[3][c]=c0>c1?(colors[0][c]+2*colors[1][c])/3:0;}colors[2][3]=255;colors[3][3]=c0>c1?255:0;for(unsigned j=0;j<4;j++){auto bits=r.U8(p+4+j);for(unsigned i=0;i<4;i++){unsigned px=x+(b%2)*4+i,py=y+(b/2)*4+j;if(px>=w||py>=h)continue;auto c=colors[(bits>>(6-i*2))&3];for(unsigned k=0;k<4;k++)out.rgba[(py*w+px)*4+k]=c[k];}}}return out;
    }
    static BodyModel Decode(std::span<const uint8_t>data){ResourceReader r{data};if(r.U32(0)!=0x62726573)throw std::invalid_argument("Invalid Mii body BRRES.");auto root=Dictionary(r,r.U16(12)+8);auto md=Dictionary(r,Find(root,"3DModels(NW4R)"));size_t m=Find(md,"model");if(r.U32(m+8)!=11)throw std::invalid_argument("Unsupported Mii body model version.");auto section=[&](unsigned j){auto p=r.U32(m+16+4*j);return p?Dictionary(r,m+p):std::vector<Entry>{};};auto nodes=section(1);std::map<std::string,std::array<float,9>> pose;
        auto animations=Dictionary(r,Find(root,"AnmChr(NW4R)"));size_t stand=Find(animations,"stand");for(auto&e:Dictionary(r,stand+r.U32(stand+16))){auto flags=r.U32(e.offset+4);size_t p=e.offset+8;std::array<float,9>a{1,1,1,0,0,0,0,0,0};auto track=[&](unsigned fmt,bool constant){float value;if(constant||!fmt)value=F(r,p);else {size_t t=e.offset+r.U32(p);if(fmt==1)value=((r.U16(t+17)>>4)*F(r,t+8))+F(r,t+12);else if(fmt==2)value=r.U16(t+18)*F(r,t+8)+F(r,t+12);else if(fmt==3)value=F(r,t+12);else if(fmt==6)value=F(r,t);else throw std::invalid_argument("Unsupported Mii standing pose.");}p+=4;return value;};if(!(flags&0x8a)){a[0]=track((flags>>25)&3,flags&(1<<13));if(flags&16)a[1]=a[2]=a[0];else {a[1]=track((flags>>25)&3,flags&(1<<14));a[2]=track((flags>>25)&3,flags&(1<<15));}}if(!(flags&0x126))for(int j=0;j<3;j++)a[3+j]=track((flags>>27)&7,flags&(1<<(16+j)));if(!(flags&0x246))for(int j=0;j<3;j++)a[6+j]=track((flags>>30)&3,flags&(1<<(19+j)));pose[e.name]=a;}
        std::map<size_t,Matrix> world;std::map<unsigned,Matrix> matrices;BodyModel result;
        for(auto&e:nodes){std::array<float,9>a;for(int j=0;j<9;j++)a[j]=F(r,e.offset+32+j*4);if(pose.contains(e.name))a=pose[e.name];auto local=SRT(a);int32_t parent=int32_t(r.U32(e.offset+92));auto global=parent?world.at(e.offset+parent)*local:local;world[e.offset]=global;matrices[r.U32(e.offset+16)]=global;if(e.name=="face_1"){result.neckY=global.v[7];result.neckZ=global.v[11];}}
        auto positions=section(2),normals=section(3),colors=section(4),uvs=section(5),materials=section(8),shapes=section(10);auto texDic=Dictionary(r,Find(root,"Textures(NW4R)"));Image texture,lightMap,highlightMap;for(auto&e:texDic){if(e.name.find("_all")!=std::string::npos)texture=Texture(r,e.offset);if(e.name=="lm_0")lightMap=Texture(r,e.offset);if(e.name=="lm_1")highlightMap=Texture(r,e.offset);}
        if(!texture.width||!lightMap.width||!highlightMap.width)throw std::invalid_argument("Missing Mii body material textures.");
        std::map<unsigned,unsigned> shapeMaterials;
        size_t draw=Find(section(0),"DrawOpa");
        for(unsigned command=0;command<1024;command++){
            unsigned op=r.U8(draw++);if(op==1)break;
            if(op!=4)throw std::invalid_argument("Unsupported Mii body draw command.");
            unsigned material=r.U16(draw),shape=r.U16(draw+2);draw+=7;
            if(material>=materials.size()||shape>=shapes.size())throw std::invalid_argument("Invalid Mii body draw material.");
            shapeMaterials[shape]=material;
            if(command==1023)throw std::invalid_argument("Unterminated Mii body draw commands.");
        }
        auto vector=[&](const std::vector<Entry>&buffers,int id,unsigned index,unsigned dim){if(id<0||unsigned(id)>=buffers.size())throw std::invalid_argument("Invalid body vertex buffer.");size_t b=buffers[id].offset;unsigned format=r.U32(b+24),shift=r.U8(b+28),stride=r.U8(b+29),count=r.U16(b+30);if(index>=count)throw std::invalid_argument("Invalid body vertex index.");size_t p=b+r.U32(b+8)+index*stride;std::array<float,3>v{};for(unsigned k=0;k<dim;k++){if(format==4)v[k]=F(r,p+k*4);else if(format==3)v[k]=int16_t(r.U16(p+k*2))/std::pow(2.f,shift);else if(format==2)v[k]=r.U16(p+k*2)/std::pow(2.f,shift);else if(format==1)v[k]=int8_t(r.U8(p+k))/std::pow(2.f,shift);else if(format==0)v[k]=r.U8(p+k)/std::pow(2.f,shift);else throw std::invalid_argument("Unsupported Mii body vertex format.");}return v;};
        for(size_t si=0;si<shapes.size();si++){size_t s=shapes[si].offset;BodyPart part;part.favoriteColor=materials.at(shapeMaterials.at(unsigned(si))).name=="mii_color";part.texture=texture;part.lightMap=lightMap;part.highlightMap=highlightMap;size_t pre=s+24+r.U32(s+32),end=pre+r.U32(s+28);uint32_t vcdLo=0,vcdHi=0;for(size_t p=pre;p<end;){unsigned cmd=r.U8(p++);if(cmd==0)continue;if(cmd==8){unsigned reg=r.U8(p++),value=r.U32(p);p+=4;if(reg==0x50)vcdLo=value;if(reg==0x60)vcdHi=value;}else if(cmd==0x10){size_t count=r.U16(p)+1;p+=4+count*4;r.Check(p,0);}else if(cmd==0x61)p+=4;else throw std::invalid_argument("Unsupported body vertex setup.");}
            std::array<unsigned,21> desc{};for(int j=0;j<9;j++)desc[j]=(vcdLo>>j)&1;for(int j=9;j<13;j++)desc[j]=(vcdLo>>(9+(j-9)*2))&3;for(int j=13;j<21;j++)desc[j]=(vcdHi>>((j-13)*2))&3;
            std::array<unsigned,10> slots{};int fixed=int32_t(r.U32(s+8));size_t p=s+36+r.U32(s+44),stop=p+r.U32(s+40);while(p<stop){unsigned cmd=r.U8(p++);if(!cmd)continue;if(cmd==0x20||cmd==0x28||cmd==0x30||cmd==0x38){unsigned index=r.U16(p),address=r.U16(p+2)&0xfff;p+=4;if(cmd==0x20){unsigned slot=address/12;if(slot>=slots.size())throw std::invalid_argument("Invalid body matrix slot.");slots[slot]=index;}continue;}if(cmd<0x80||cmd>0xbf)throw std::invalid_argument("Unsupported Mii body primitive.");unsigned count=r.U16(p);p+=2;std::vector<Mesh::Vertex>v;for(unsigned i=0;i<count;i++){std::array<unsigned,21> index{};for(int j=0;j<21;j++)if(desc[j]){if(desc[j]==1&&j>=9)throw std::invalid_argument("Direct body attributes unsupported.");index[j]=desc[j]==3?r.U16(p):r.U8(p);p+=desc[j]==3?2:1;}auto pos=vector(positions,int16_t(r.U16(s+72)),index[9],3),n=vector(normals,int16_t(r.U16(s+74)),index[10],3),uv=vector(uvs,int16_t(r.U16(s+80)),index[13],2);unsigned matrix=fixed>=0?unsigned(fixed):slots.at(index[0]/3);auto mat=matrices.at(matrix);pos=mat.Apply(pos);n=mat.Apply(n,true);Mesh::Vertex q{pos[0],pos[1],pos[2],n[0],n[1],n[2],uv[0],uv[1]};if(desc[11]){size_t b=colors.at(int16_t(r.U16(s+76))).offset;if(index[11]>=r.U16(b+30)||r.U32(b+24)!=5)throw std::invalid_argument("Invalid body color.");size_t c=b+r.U32(b+8)+index[11]*r.U8(b+28);q.red=r.U8(c)/255.f;q.green=r.U8(c+1)/255.f;q.blue=r.U8(c+2)/255.f;q.alpha=r.U8(c+3)/255.f;}v.push_back(q);}
                auto tri=[&](unsigned a,unsigned b,unsigned c){part.mesh.triangles.insert(part.mesh.triangles.end(),{v.at(a),v.at(b),v.at(c)});};switch(cmd&0xf8){case 0x80:for(unsigned j=0;j+3<count;j+=4){tri(j,j+1,j+2);tri(j,j+2,j+3);}break;case 0x90:for(unsigned j=0;j+2<count;j+=3)tri(j,j+1,j+2);break;case 0x98:for(unsigned j=2;j<count;j++)tri(j-2+j%2,j-1-j%2,j);break;case 0xa0:for(unsigned j=2;j<count;j++)tri(0,j-1,j);break;default:throw std::invalid_argument("Unsupported body primitive type.");}}
            result.parts.push_back(std::move(part));}return result;
    }
public:
    explicit BodyResources(std::span<const uint8_t>archive){std::vector<uint8_t> unpacked;if(ResourceReader{archive}.U32(0)==0x59617a30){ResourceReader r{archive};auto n=r.U32(4);if(n>16*1024*1024)throw std::invalid_argument("Oversized body archive.");size_t p=16;while(unpacked.size()<n){unsigned bits=r.U8(p++);for(unsigned b=0;b<8&&unpacked.size()<n;b++){if(bits&(128>>b))unpacked.push_back(r.U8(p++));else{unsigned a=r.U8(p++),c=r.U8(p++),distance=((a&15)<<8)+c+1,length=a>>4;length=length?length+2:r.U8(p++)+18;if(distance>unpacked.size()||length>n-unpacked.size())throw std::invalid_argument("Invalid compressed body archive.");for(unsigned k=0;k<length;k++)unpacked.push_back(unpacked[unpacked.size()-distance]);}}}archive=unpacked;}ResourceReader r{archive};if(r.U32(0)!=0x55aa382d)throw std::invalid_argument("Invalid Mii body archive.");size_t root=r.U32(4),n=r.U32(root+8),strings=root+n*12;if(n>1024)throw std::invalid_argument("Invalid Mii body entries.");for(unsigned gender=0;gender<2;gender++){std::string name=gender?"ma_mii_f.brres":"ma_mii_m.brres";bool found=false;for(unsigned i=1;i<n;i++){size_t e=root+i*12;auto word=r.U32(e);if(!(word>>24)&&Name(r,strings+(word&0xffffff))==name){models[gender]=Decode(r.Slice(r.U32(e+4),r.U32(e+8)));found=true;break;}}if(!found)throw std::invalid_argument("Missing imported Mii body model.");for(unsigned i=1;i<n;i++){size_t e=root+i*12;auto word=r.U32(e);if(!(word>>24)&&Name(r,strings+(word&0xffffff))=="miiDispParam.bin"){size_t t=r.U32(e+4);if(r.U32(t)<1||r.U32(e+8)<16)throw std::invalid_argument("Invalid Mii attachment parameters.");for(unsigned j=0;j<3;j++)models[gender].headAttachment[j]=F(r,t+4+j*4);}}}}
    const BodyModel&Model(bool female)const{return models[female?1:0];}
};
}
